### ISSUE TITLE
Druid 0.9.2, Tranquility rollup set false but not work.

### ISSUE THREAD

**Issue by sylphy-zh** [apache/incubator-druid#3861]
When I use tranquility ingest the realtime data. The maven version is 0.8.2.

```
<groupId>io.druid</groupId>
  <artifactId>tranquility-core_2.11</artifactId>
 <version>0.8.2</version>
```
then exclusion the 0.9.1 druid dependencies, add the 0.9.2

```
<dependency>
    	<groupId>io.druid</groupId>
    	<artifactId>druid-server</artifactId>
    	<version>0.9.2</version>
</dependency>
<dependency>
    	<groupId>io.druid</groupId>
    	<artifactId>druid-processing</artifactId>
    	<version>0.9.2</version>
</dependency>
<dependency>
    	<groupId>io.druid</groupId>
    	<artifactId>druid-api</artifactId>
        <version>0.9.2</version>
</dependency>
```
my dataSchema.yaml file as below：

```
dataSources:
  - { properties: { task.partitions: '1' }, spec: { dataSchema: { dataSource: foo, parser: { type: string, parseSpec: { format: json, dimensionsSp
ec: { dimensions: [key, pid, uid, idfv, sdkver, sr, sys, mbos, ver, from, net, ip, city, country, province, mbl, sjp, sjm, ntm, source, guid, hdid, new_flag
] }, timestampSpec: { column: time, format: 'yyyy-MM-dd HH:mm' } } }, metricsSpec: [{ name: count, type: count }, { name: user_stats, type: hyperUnique, fie
ldName: key }, { name: hdid_stats, type: hyperUnique, fieldName: hdid }], granularitySpec: { type: uniform, segmentGranularity: hour, queryGranularity: none
, rollup: false } }, tuningConfig: { type: realtime, intermediatePersistPeriod: PT45S, maxRowInMemory: 75000, buildV9Directly: true, windowPeriod: PT10M, shardSpec: { type: numbered } } } }
properties:
  zookeeper.connect: 'xxxx:2081'
  druid.selectors.indexing.serviceName: druid/overlord
  druidBeam.taskLocator: overlord
  druidBeam.overlordPollPeriod: PT5S
```

Because some reason ,I don't want use rollup. And original data is my need. when I see 0.9.2 has ability to disable rollup,I decide to use it. But when I want to set the rollup false, I see logs, the rollup value is still true. It's not work.

```
"granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "HOUR",
        "queryGranularity" : {
          "type" : "none"
        },
        "rollup" : true,
        "intervals" : null
      }
```
except this, when I change the shardSpec type is numbered, the log still linear.

   ```
   "shardSpec" : {
        "type" : "linear",
        "partitionNum" : 0
      },
```
I tried many times ,but still get the same result. Is there any problem in my config?
I think the latest tranquility version 0.8.2 source code when get data source config is not match the druid 0.9.2. May be this is. Anyone has some ideas?
