### ISSUE TITLE
Druid docker container with Local deep storage

### ISSUE THREAD

**Issue by adilev26** [apache/incubator-druid#9049]
using the following compose file,
for some reason it seems that the segments are not being stored, neither the index task logs.
the index task shows SUCCESS but the log shows 404 Error.
exception in the logs below shows that it can't find the segment file.

**environment**
DRUID_XMX=1g
DRUID_XMS=1g
DRUID_MAXNEWSIZE=250m
DRUID_NEWSIZE=250m
DRUID_MAXDIRECTMEMORYSIZE=5120m

druid_emitter_logging_logLevel=debug

druid_extensions_loadList=["druid-histogram", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage", "druid-kafka-indexing-service"]

druid_zk_service_host=zookeeper

druid_metadata_storage_host=
druid_metadata_storage_type=postgresql
druid_metadata_storage_connector_connectURI=jdbc:postgresql://postgres:5432/druid
druid_metadata_storage_connector_user=druid
druid_metadata_storage_connector_password=druid

druid_coordinator_balancer_strategy=cachingCost

druid_indexer_runner_javaOptsArray=["-server", "-Xmx1g", "-Xms1g", "-XX:MaxDirectMemorySize=4g", "-Duser.timezone=UTC", "-Dfile.encoding=UTF-8", "-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"]
druid_indexer_fork_property_druid_processing_buffer_sizeBytes=157286400
druid_processing_buffer_sizeBytes=157286400
druid_processing_numMergeBuffers=2
druid_processing_numThreads=1

druid_storage_type=local
druid_storage_storageDirectory=/opt/druid/var/segments

DRUID_LOG4J=<?xml version="1.0" encoding="UTF-8" ?><Configuration status="WARN"><Appenders><Console name="Console" target="SYSTEM_OUT"><PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/></Console></Appenders><Loggers><Root level="info"><AppenderRef ref="Console"/></Root><Logger name="org.apache.druid.jetty.RequestLog" additivity="false" level="DEBUG"><AppenderRef ref="Console"/></Logger></Loggers></Configuration>

**compose file:**

`version: "2.1"

volumes:
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  overlord_var: {}
  router_var: {}

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=aristo1
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5
    environment:
      - ZOO_MY_ID=1

  coordinator:
    image: apache/incubator-druid:0.16.0-incubating
    container_name: coordinator
    volumes:
      - coordinator_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
    ports:
      - "3001:8081"
    command:
      - coordinator
    env_file:
      - environment

  broker:
    image: apache/incubator-druid:0.16.0-incubating
    container_name: broker
    volumes:
      - broker_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "3002:8082"
    command:
      - broker
    env_file:
      - environment

  historical:
    image: apache/incubator-druid:0.16.0-incubating
    container_name: historical
    volumes:
      - historical_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "3003:8083"
    command:
      - historical
    env_file:
      - environment

  overlord:
    image: apache/incubator-druid:0.16.0-incubating
    container_name: overlord
    volumes:
      - overlord_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
    ports:
      - "4000:8090"
    command:
      - overlord
    env_file:
      - environment

  middlemanager:
    image: apache/incubator-druid:0.16.0-incubating
    container_name: middlemanager
    volumes:
      - middle_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "4001:8091"
    command:
      - middleManager
    env_file:
      - environment

  router:
    image: apache/incubator-druid:0.16.0-incubating
    container_name: router
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "4008:8888"
    command:
      - router
    env_file:
      - environment
`

historical       | 2019-12-16T11:43:45,810 ERROR [ZKCoordinator--3] org.apache.druid.server.coordination.SegmentLoadDropHandler - Failed to load segment for dataSource:
historical       | Caused by: java.lang.IllegalArgumentException: Instantiation of [simple type, class org.apache.druid.segment.loading.LocalLoadSpec] value failed: [/opt/druid/var/segments/wikipedia/2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z/2019-12-16T11:42:49.059Z/0/index.zip] does not exist
historical       | Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class org.apache.druid.segment.loading.LocalLoadSpec] value failed: [/opt/druid/var/segments/wikipedia/2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z/2019-12-16T11:42:49.059Z/0/index.zip] does not exist

**Comment by adilev26** [comment]
because the middle manager and the historical have a different volume for storage, the middle manager has wrote the segment in it's own volume which is not the same as the historical one.

for local storage to work, the historical and the middle manager must have the same volume for storage.

set the following in the environment file:
```
druid_storage_type=local
druid_storage_storageDirectory=/opt/druid/var/segments
```


and change the docker-compose.yml to use the following:
```
  historical:
    image: apache/incubator-druid:0.16.1-incubating
    container_name: historical
    volumes:
      - data_node_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "3003:8083"
    command:
      - historical
    env_file:
      - environment

  middlemanager:
    image: apache/incubator-druid:0.16.1-incubating
    container_name: middlemanager
    volumes:
      - data_node_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "4001:8091"
    command:
      - middleManager
    env_file:
      - environment
```
